import { GoogleGenAI, Modality } from "@google/genai";

export async function generateHeadshot(base64Image: string, mimeType: string, prompt: string): Promise<string> {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // The Gemini API requires just the base64 string, without the data URI prefix.
    const pureBase64 = base64Image.split(',')[1];
    if (!pureBase64) {
        throw new Error("Invalid base64 image data.");
    }

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: pureBase64,
                            mimeType: mimeType,
                        },
                    },
                    {
                        text: prompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        // Find the image part in the response
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.mimeType.startsWith('image/')) {
                return part.inlineData.data;
            }
        }

        throw new Error("No image was generated by the API.");

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("The AI model failed to generate an image. This might be due to a safety policy or an internal error.");
    }
}
